import hashlib
import json
import logging
import os


class UploadManager:

    def __init__(self, *, trace, basepath=None, bucket=None, s3=None):
        self.trace = trace
        self.basepath = None
        self.bucket = None
        self.s3 = None

    def configure(self, *, s3=None, bucket=None, basepath=None):
        if s3:
            self.s3 = s3
        if bucket:
            self.bucket = bucket
        if basepath:
            self.basepath = basepath

    def upload(self, *, activity):
        """
        Uploads files generated by the given activity if there are any to a
        subdirectory named after the activity_id.
        Adds a manifest file to the subdirectory that includes the file name,
        size and sha256 checksum.

        Does not upload the provenance.
        """
        activity_id = activity.get_activity_id()
        file_list = self.trace.get_files(generator=activity)
        if not file_list:
            logging.debug("No files for generator %s", activity_id)
            return

        dest_path = os.path.join(self.basepath, activity_id)
        self._upload_directory(path=dest_path, file_list=file_list)

    def upload_provenance(self):
        """
        Uploads the provenance stored in this manager.
        """
        self._put_provenance(path=self.basepath, trace=self.trace)

    def _upload_directory(self, *, path, file_list):
        files = list()
        for file_entity in file_list:
            logging.debug("Uploading %s", file_entity.name)
            content_type = self._get_content_type(file_entity)
            try:
                file_object = file_entity.upload.data
            except ConnectionError:
                logging.error(
                    "Upload of file %s (%s) failed due to closed connection",
                    file_entity.id, file_entity.name
                )
                raise
            hash_sha = hashlib.sha256()
            hash_sha.update(object)
            file_entity.check_sum = str(hash_sha.hexdigest())
            self._put_object(path=path,
                             filename=file_entity.name,
                             file_object=file_object,
                             content_type=content_type)
            files.append({
                'name': file_entity.name,
                'size': file_entity.size,
                'sha256': file_entity.check_sum
            })
        self._put_object(path=path,
                         filename='upload_manifest.json',
                         file_object=json.dumps(files, indent=2),
                         content_type="application/json"
                         )

    def _get_content_type(self, file_entity):
        content_type = file_entity.upload.upload_content_type
        if file_entity.type == 'FCS':
            content_type = 'application/octet-stream'
        elif file_entity.type == 'CSV':
            content_type = 'text/csv'
        return content_type

    def _put_object(self, *, path, filename, file_object, content_type):
        key_path = os.path.join(path, filename)
        logging.info("upload %s to %s", key_path, self.bucket)
        self.s3.put_object(
            Body=file_object,
            Bucket=self.bucket,
            ContentType=content_type,
            Key=key_path
        )

    def _put_provenance(self, *, path, trace):
        self._put_object(
            path=path,
            filename='provenance_dump.json',
            file_object=str(json.dumps(trace.as_dict(), indent=2)),
            content_type='application/json'
        )


class S3DumpProxy:

    def __init__(self, root_dir):
        self.root_dir = root_dir

    def put_object(self, *, Body, Bucket, ContentType, Key):
        # make directory root_dir/Bucket/Key minus file name
        # write Body to
        path = os.path.join(*[self.root_dir, Bucket, Key])
        directory_path = os.path.join(*(str.split(path, os.sep)[:-1]))
        if ContentType == 'application/json':
            output = Body
        else:
            output = "would write file to {}".format(path)
        if not os.path.exists(directory_path):
            os.makedirs(directory_path)
        with open(path, 'w') as file:
            file.write(output)
